services:
  unigrab-ui:
    container_name: unigrabuicontainer
    build: .
    image: unigrab-ui:latest
    ports:
      - 8080:80
    expose:
      - 80
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
