stages:
  - unit_test
  - build_image
  - deploy_dev

unit_test:
  stage: unit_test
  script:
    - # Add commands to run your unit tests here
  only:
    - master

build_image:
  stage: build_image
  script:
    - docker build -t $DOCKER_IMAGE_NAME:latest -f Dockerfile .
    - docker tag $DOCKER_IMAGE_NAME:latest $ACR_NAME/$DOCKER_IMAGE_NAME:latest
    - echo $AZURE_SERVICE_CONNECTION_NAME | docker login $ACR_NAME -u $AZURE_SERVICE_CONNECTION_NAME --password-stdin
    - docker push $ACR_NAME/$DOCKER_IMAGE_NAME:latest
  only:
    - master
  tags:
    - docker  # This assumes you have a runner tagged as "docker" for building and pushing Docker images
  allow_failure: false

deploy:
  stage: deploy_dev
  script:
    - # Add commands to deploy the application to Azure ACR here
  only:
    - master
  allow_failure: false











#stages:
#  - build_dev
  - push_dev

build_dev:
  stage: build_dev
  script:
    - chmod +x start-dev.sh
    - ./start-dev.sh
    - docker build -t $DOCKER_IMAGE_NAME_DEV -f Dockerfile.dev .

push_dev:
  stage: push_dev
  only:
    - master
  script:
    - echo $CONTAINER_REGISTRY_PASSWORD | docker login $ACR_DEV -u $CONTAINER_REGISTRY_NAME --password-stdin
    - docker push $ACR_DEV/$DOCKER_IMAGE_NAME