# Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

# Database
DATABASE_HOST: unigrab-db.postgres.database.azure.com
DATABASE_PORT: 5432
DATABASE_NAME: unigrab-dev
DATABASE_USERNAME: unigrab_db@unigrab-db
DATABASE_PASSWORD: root@TOOR

# AWS
AWS_ACCESS_KEY_ID: secrete
AWS_SECRET_ACCESS_KEY: secrete
AWS_REGION: us-east-1
AWS_BUCKET: unigrab-data
AWS_IMAGE_BASE_URL: users/images/

# JWT
JWT_SECRET: 404E635266556A586E3272357538745678IO4M5RFU7YE6FYU7F6IJ9VK7I5UD5YV3BU3EI7NMO65MN1VC3BU9EVY2C0BUN3IE9ON4BU2V7EYC5BU5NIO7EI8BC5UE7BN9CIO5IB82F413F4428472B4B6250645367566B5970

